# Generated by Django 4.2.8 on 2025-12-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_column='TABLE_NAME', max_length=100)),
                ('action', models.CharField(db_column='ACTION', max_length=50)),
                ('old_data', models.TextField(blank=True, db_column='OLD_DATA', null=True)),
                ('new_data', models.TextField(blank=True, db_column='NEW_DATA', null=True)),
                ('changed_by', models.CharField(blank=True, db_column='CHANGED_BY', max_length=100, null=True)),
                ('changed_date', models.DateTimeField(auto_now_add=True, db_column='CHANGED_DATE')),
            ],
            options={
                'verbose_name': 'Log kiểm toán',
                'verbose_name_plural': 'Log kiểm toán',
                'db_table': 'AUDIT_LOGS',
                'ordering': ['-changed_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedIps',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ip_address', models.CharField(db_column='IP_ADDRESS', max_length=45, unique=True)),
                ('reason', models.CharField(db_column='REASON', max_length=100)),
                ('blocked_at', models.DateTimeField(auto_now_add=True, db_column='BLOCKED_AT')),
                ('blocked_until', models.DateTimeField(blank=True, db_column='BLOCKED_UNTIL', null=True)),
            ],
            options={
                'verbose_name': 'IP bị chặn',
                'verbose_name_plural': 'Danh sách IP bị chặn',
                'db_table': 'BLOCKED_IPS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FailedLoginAttempts',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ip_address', models.CharField(db_column='IP_ADDRESS', max_length=45)),
                ('username_or_email', models.CharField(blank=True, db_column='USERNAME_OR_EMAIL', max_length=200, null=True)),
                ('attempt_time', models.DateTimeField(auto_now_add=True, db_column='ATTEMPT_TIME')),
                ('user_agent', models.TextField(blank=True, db_column='USER_AGENT', null=True)),
            ],
            options={
                'verbose_name': 'Lần đăng nhập thất bại',
                'verbose_name_plural': 'Lần đăng nhập thất bại',
                'db_table': 'FAILED_LOGIN_ATTEMPTS',
                'ordering': ['-attempt_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('makh', models.AutoField(db_column='MAKH', primary_key=True, serialize=False)),
                ('hoten', models.CharField(db_column='HOTEN', max_length=200)),
                ('gioitinh', models.BooleanField(blank=True, db_column='GIOITINH', null=True)),
                ('diachi', models.CharField(blank=True, db_column='DIACHI', max_length=500, null=True)),
                ('sdt', models.CharField(blank=True, db_column='SDT', max_length=15, null=True)),
                ('email', models.CharField(db_column='EMAIL', max_length=200, unique=True)),
                ('ngaysinh', models.DateField(blank=True, db_column='NGAYSINH', null=True)),
                ('cccd', models.CharField(blank=True, db_column='CCCD', max_length=20, null=True)),
                ('trangthai', models.BooleanField(db_column='TRANGTHAI', default=True)),
                ('tg_tao', models.DateTimeField(blank=True, db_column='TG_TAO', null=True)),
                ('is_2fa_enabled', models.BooleanField(db_column='IS_2FA_ENABLED', default=False)),
                ('totp_secret', models.CharField(blank=True, db_column='TOTP_SECRET', max_length=32, null=True)),
                ('is_locked', models.BooleanField(db_column='IS_LOCKED', default=False)),
                ('locked_until', models.DateTimeField(blank=True, db_column='LOCKED_UNTIL', null=True)),
                ('last_password_change', models.DateTimeField(blank=True, db_column='LAST_PASSWORD_CHANGE', null=True)),
                ('google_id', models.CharField(blank=True, db_column='GOOGLE_ID', max_length=255, null=True)),
                ('oauth_provider', models.CharField(blank=True, db_column='OAUTH_PROVIDER', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'db_table': 'KHACHHANG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('success', models.BooleanField(db_column='SUCCESS')),
                ('ip_address', models.CharField(db_column='IP_ADDRESS', max_length=45)),
                ('user_agent', models.TextField(blank=True, db_column='USER_AGENT', null=True)),
                ('device_type', models.CharField(blank=True, db_column='DEVICE_TYPE', max_length=50, null=True)),
                ('os_family', models.CharField(blank=True, db_column='OS_FAMILY', max_length=50, null=True)),
                ('browser_family', models.CharField(blank=True, db_column='BROWSER_FAMILY', max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_column='COUNTRY', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='CITY', max_length=100, null=True)),
                ('failure_reason', models.CharField(blank=True, db_column='FAILURE_REASON', max_length=100, null=True)),
                ('used_2fa', models.BooleanField(db_column='USED_2FA', default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='TIMESTAMP')),
            ],
            options={
                'verbose_name': 'Lịch sử đăng nhập',
                'verbose_name_plural': 'Lịch sử đăng nhập',
                'db_table': 'LOGIN_HISTORY',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityLogs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_column='ACTION_TYPE', max_length=100)),
                ('ip_address', models.CharField(db_column='IP_ADDRESS', max_length=45)),
                ('details', models.TextField(blank=True, db_column='DETAILS', null=True)),
                ('log_time', models.DateTimeField(auto_now_add=True, db_column='LOG_TIME')),
            ],
            options={
                'verbose_name': 'Log bảo mật',
                'verbose_name_plural': 'Log bảo mật',
                'db_table': 'SECURITY_LOGS',
                'ordering': ['-log_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('matk', models.AutoField(db_column='MATK', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='USERNAME', max_length=100, null=True, unique=True)),
                ('password_hash', models.BinaryField(blank=True, db_column='PASSWORD_HASH', max_length='max', null=True)),
                ('password_salt', models.CharField(blank=True, db_column='PASSWORD_SALT', max_length=36, null=True)),
                ('is_locked', models.BooleanField(blank=True, db_column='IS_LOCKED', default=False, null=True)),
                ('lock_time', models.DateTimeField(blank=True, db_column='LOCK_TIME', null=True)),
                ('failed_login_count', models.IntegerField(blank=True, db_column='FAILED_LOGIN_COUNT', default=0, null=True)),
                ('two_factor_enabled', models.BooleanField(blank=True, db_column='TWO_FACTOR_ENABLED', default=False, null=True)),
                ('two_factor_secret', models.CharField(blank=True, db_column='TWO_FACTOR_SECRET', max_length=100, null=True)),
                ('oauth_provider', models.CharField(blank=True, db_column='OAUTH_PROVIDER', max_length=50, null=True)),
                ('oauth_id', models.CharField(blank=True, db_column='OAUTH_ID', max_length=200, null=True)),
                ('last_login_ip', models.CharField(blank=True, db_column='LAST_LOGIN_IP', max_length=45, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, db_column='LAST_LOGIN_TIME', null=True)),
                ('tg_tao', models.DateTimeField(blank=True, db_column='TG_TAO', null=True)),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Tài khoản',
                'db_table': 'TAIKHOAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaitro',
            fields=[
                ('mavt', models.AutoField(db_column='MAVT', primary_key=True, serialize=False)),
                ('tenvt', models.CharField(db_column='TENVT', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Vai trò',
                'verbose_name_plural': 'Vai trò',
                'db_table': 'VAITRO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_key', models.CharField(db_column='QUESTION_KEY', max_length=50)),
                ('answer_hash', models.CharField(db_column='ANSWER_HASH', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('makh', models.OneToOneField(db_column='MAKH', on_delete=django.db.models.deletion.CASCADE, related_name='security_question_obj', to='accounts.khachhang')),
            ],
            options={
                'verbose_name': 'Câu hỏi bảo mật',
                'verbose_name_plural': 'Câu hỏi bảo mật',
                'db_table': 'SECURITY_QUESTIONS',
                'managed': True,
            },
        ),
    ]
