-- ============================================
-- PHONGTRO.VN - DATABASE SETUP SCRIPT
-- Optimized for Django + SQL Server 2019
-- Security-focused design
-- ============================================

USE [QuanLyChoThuePhongTro];
GO

-- ============================================
-- 1. DROP EXISTING TABLES (Clean slate)
-- ============================================
-- Comment out this section if you want to keep existing data

IF OBJECT_ID('LOGIN_HISTORY', 'U') IS NOT NULL DROP TABLE LOGIN_HISTORY;
IF OBJECT_ID('DANHGIA', 'U') IS NOT NULL DROP TABLE DANHGIA;
IF OBJECT_ID('TINNHAN', 'U') IS NOT NULL DROP TABLE TINNHAN;
IF OBJECT_ID('THONGBAO', 'U') IS NOT NULL DROP TABLE THONGBAO;
IF OBJECT_ID('HENXEMTRO', 'U') IS NOT NULL DROP TABLE HENXEMTRO;
IF OBJECT_ID('THUETRO', 'U') IS NOT NULL DROP TABLE THUETRO;
IF OBJECT_ID('HINHANH', 'U') IS NOT NULL DROP TABLE HINHANH;
IF OBJECT_ID('PHONGTRO', 'U') IS NOT NULL DROP TABLE PHONGTRO;
IF OBJECT_ID('NHATRO', 'U') IS NOT NULL DROP TABLE NHATRO;
IF OBJECT_ID('YCLAMCHUTRO', 'U') IS NOT NULL DROP TABLE YCLAMCHUTRO;
IF OBJECT_ID('BLOCKED_IPS', 'U') IS NOT NULL DROP TABLE BLOCKED_IPS;
IF OBJECT_ID('SECURITY_LOGS', 'U') IS NOT NULL DROP TABLE SECURITY_LOGS;
IF OBJECT_ID('AUDIT_LOGS', 'U') IS NOT NULL DROP TABLE AUDIT_LOGS;
IF OBJECT_ID('FAILED_LOGIN_ATTEMPTS', 'U') IS NOT NULL DROP TABLE FAILED_LOGIN_ATTEMPTS;
IF OBJECT_ID('KHACHHANG', 'U') IS NOT NULL DROP TABLE KHACHHANG;
IF OBJECT_ID('TAIKHOAN', 'U') IS NOT NULL DROP TABLE TAIKHOAN;
IF OBJECT_ID('VAITRO', 'U') IS NOT NULL DROP TABLE VAITRO;

PRINT N'Dropped existing tables';
GO

-- ============================================
-- 2. CORE TABLES
-- ============================================

-- VAITRO (Roles)
CREATE TABLE VAITRO (
    MAVT INT IDENTITY(1,1) PRIMARY KEY,
    TENVT NVARCHAR(50) NOT NULL UNIQUE
);
PRINT N'Created: VAITRO';
GO

-- TAIKHOAN (Accounts)
CREATE TABLE TAIKHOAN (
    MATK INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME VARCHAR(100) UNIQUE,
    PASSWORD_HASH VARBINARY(32) NOT NULL,
    PASSWORD_SALT VARCHAR(36) NOT NULL,
    IS_LOCKED BIT DEFAULT 0,
    LOCK_TIME DATETIME NULL,
    FAILED_LOGIN_COUNT INT DEFAULT 0,
    TWO_FACTOR_ENABLED BIT DEFAULT 0,
    TWO_FACTOR_SECRET VARCHAR(100) NULL,
    OAUTH_PROVIDER VARCHAR(50) NULL,
    OAUTH_ID VARCHAR(200) NULL,
    LAST_LOGIN_IP VARCHAR(45) NULL,
    LAST_LOGIN_TIME DATETIME NULL,
    TG_TAO DATETIME DEFAULT GETDATE()
);
CREATE INDEX IX_TAIKHOAN_USERNAME ON TAIKHOAN(USERNAME);
PRINT N'Created: TAIKHOAN';
GO

-- KHACHHANG (Customers)
CREATE TABLE KHACHHANG (
    MAKH INT IDENTITY(1,1) PRIMARY KEY,
    MATK INT FOREIGN KEY REFERENCES TAIKHOAN(MATK) ON DELETE CASCADE,
    MAVT INT FOREIGN KEY REFERENCES VAITRO(MAVT),
    HOTEN NVARCHAR(200) NOT NULL,
    GIOITINH BIT NULL,
    DIACHI NVARCHAR(500) NULL,
    SDT VARCHAR(15) NULL,
    EMAIL VARCHAR(200) UNIQUE NOT NULL,
    NGAYSINH DATE NULL,
    CCCD VARCHAR(20) NULL,
    TRANGTHAI BIT DEFAULT 1,
    TG_TAO DATETIME DEFAULT GETDATE(),
    IS_2FA_ENABLED BIT DEFAULT 0,
    TOTP_SECRET VARCHAR(32) NULL,
    IS_LOCKED BIT DEFAULT 0,
    LOCKED_UNTIL DATETIME NULL,
    LAST_PASSWORD_CHANGE DATETIME NULL,
    GOOGLE_ID VARCHAR(255) NULL,
    OAUTH_PROVIDER VARCHAR(50) NULL
);
CREATE INDEX IX_KHACHHANG_EMAIL ON KHACHHANG(EMAIL);
CREATE INDEX IX_KHACHHANG_MATK ON KHACHHANG(MATK);
PRINT N'Created: KHACHHANG';
GO

-- LOGIN_HISTORY
CREATE TABLE LOGIN_HISTORY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MAKH INT NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MAKH) ON DELETE CASCADE,
    SUCCESS BIT NOT NULL,
    IP_ADDRESS VARCHAR(45) NOT NULL,
    USER_AGENT NVARCHAR(MAX) NULL,
    DEVICE_TYPE VARCHAR(50) NULL,
    OS_FAMILY VARCHAR(50) NULL,
    BROWSER_FAMILY VARCHAR(50) NULL,
    COUNTRY VARCHAR(100) NULL,
    CITY VARCHAR(100) NULL,
    FAILURE_REASON VARCHAR(100) NULL,
    USED_2FA BIT DEFAULT 0,
    TIMESTAMP DATETIME DEFAULT GETDATE()
);
CREATE INDEX IX_LOGIN_HISTORY_MAKH ON LOGIN_HISTORY(MAKH, TIMESTAMP DESC);
PRINT N'Created: LOGIN_HISTORY';
GO

-- ============================================
-- 3. ROOM MANAGEMENT TABLES
-- ============================================

-- NHATRO (Rental Houses)
CREATE TABLE NHATRO (
    MANT INT IDENTITY(1,1) PRIMARY KEY,
    MAKH INT FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    TENNT NVARCHAR(200) NOT NULL,
    DIACHI NVARCHAR(500) NOT NULL,
    MOTA NVARCHAR(MAX) NULL,
    GIADIEN DECIMAL(18,2) DEFAULT 0,
    GIANUOC DECIMAL(18,2) DEFAULT 0,
    TRANGTHAI BIT DEFAULT 1,
    TG_TAO DATETIME DEFAULT GETDATE()
);
CREATE INDEX IX_NHATRO_MAKH ON NHATRO(MAKH);
PRINT N'Created: NHATRO';
GO

-- PHONGTRO (Rooms)
CREATE TABLE PHONGTRO (
    MAPT INT IDENTITY(1,1) PRIMARY KEY,
    MANT INT FOREIGN KEY REFERENCES NHATRO(MANT) ON DELETE CASCADE,
    TENPT NVARCHAR(200) NOT NULL,
    MOTA NVARCHAR(MAX) NULL,
    DIENTICH FLOAT NULL,
    GIATIEN DECIMAL(18,2) NOT NULL,
    SONGUOIO INT DEFAULT 0,
    TRANGTHAI NVARCHAR(50) DEFAULT N'Còn trống',
    TG_TAO DATETIME DEFAULT GETDATE()
);
CREATE INDEX IX_PHONGTRO_MANT ON PHONGTRO(MANT);
CREATE INDEX IX_PHONGTRO_TRANGTHAI ON PHONGTRO(TRANGTHAI);
PRINT N'Created: PHONGTRO';
GO

-- HINHANH (Room Images)
CREATE TABLE HINHANH (
    MAHA INT IDENTITY(1,1) PRIMARY KEY,
    MAPT INT FOREIGN KEY REFERENCES PHONGTRO(MAPT) ON DELETE CASCADE,
    DUONGDAN NVARCHAR(500) NOT NULL,
    MOTA NVARCHAR(200) NULL,
    TG_TAO DATETIME DEFAULT GETDATE()
);
PRINT N'Created: HINHANH';
GO

-- ============================================
-- 4. BOOKING & RENTAL TABLES
-- ============================================

-- HENXEMTRO (Viewing Appointments)
CREATE TABLE HENXEMTRO (
    MAHXT INT IDENTITY(1,1) PRIMARY KEY,
    MAPT INT FOREIGN KEY REFERENCES PHONGTRO(MAPT),
    MAKH INT FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    NGAYHEN DATETIME NOT NULL,
    GHICHU NVARCHAR(500) NULL,
    TRANGTHAI NVARCHAR(50) DEFAULT N'Chờ xác nhận',
    TG_TAO DATETIME DEFAULT GETDATE()
);
PRINT N'Created: HENXEMTRO';
GO

-- THUETRO (Rentals)
CREATE TABLE THUETRO (
    MATT INT IDENTITY(1,1) PRIMARY KEY,
    MAPT INT FOREIGN KEY REFERENCES PHONGTRO(MAPT),
    MAKH INT FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    NGAYBATDAU DATE NOT NULL,
    NGAYKETTHUC DATE NULL,
    TIENCOC DECIMAL(18,2) DEFAULT 0,
    TRANGTHAI NVARCHAR(50) DEFAULT N'Đang thuê',
    TG_TAO DATETIME DEFAULT GETDATE()
);
PRINT N'Created: THUETRO';
GO

-- DANHGIA (Reviews)
CREATE TABLE DANHGIA (
    MADG INT IDENTITY(1,1) PRIMARY KEY,
    MAPT INT FOREIGN KEY REFERENCES PHONGTRO(MAPT) ON DELETE CASCADE,
    MAKH INT FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    SAO INT CHECK (SAO BETWEEN 1 AND 5),
    BINHLUAN NVARCHAR(MAX) NULL,
    TG_TAO DATETIME DEFAULT GETDATE()
);
PRINT N'Created: DANHGIA';
GO

-- ============================================
-- 5. COMMUNICATION TABLES
-- ============================================

-- TINNHAN (Messages)
CREATE TABLE TINNHAN (
    MATN INT IDENTITY(1,1) PRIMARY KEY,
    MAKH_GUI INT FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    MAKH_NHAN INT FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    NOIDUNG NVARCHAR(MAX) NOT NULL,
    DADOC BIT DEFAULT 0,
    TG_GUI DATETIME DEFAULT GETDATE()
);
PRINT N'Created: TINNHAN';
GO

-- THONGBAO (Notifications)
CREATE TABLE THONGBAO (
    MATB INT IDENTITY(1,1) PRIMARY KEY,
    MAKH INT FOREIGN KEY REFERENCES KHACHHANG(MAKH) ON DELETE CASCADE,
    TIEUDE NVARCHAR(200) NOT NULL,
    NOIDUNG NVARCHAR(MAX) NULL,
    LOAI VARCHAR(50) DEFAULT 'info',
    DADOC BIT DEFAULT 0,
    TG_TAO DATETIME DEFAULT GETDATE()
);
PRINT N'Created: THONGBAO';
GO

-- ============================================
-- 6. SECURITY TABLES
-- ============================================

-- FAILED_LOGIN_ATTEMPTS
CREATE TABLE FAILED_LOGIN_ATTEMPTS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IP_ADDRESS VARCHAR(45) NOT NULL,
    USERNAME_OR_EMAIL VARCHAR(200) NULL,
    ATTEMPT_TIME DATETIME DEFAULT GETDATE(),
    USER_AGENT NVARCHAR(MAX) NULL
);
CREATE INDEX IX_FAILED_LOGIN_IP_TIME ON FAILED_LOGIN_ATTEMPTS(IP_ADDRESS, ATTEMPT_TIME DESC);
PRINT N'Created: FAILED_LOGIN_ATTEMPTS';
GO

-- BLOCKED_IPS
CREATE TABLE BLOCKED_IPS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IP_ADDRESS VARCHAR(45) NOT NULL UNIQUE,
    REASON VARCHAR(100) NOT NULL,
    BLOCKED_AT DATETIME DEFAULT GETDATE(),
    BLOCKED_UNTIL DATETIME NULL,
    BLOCKED_BY INT FOREIGN KEY REFERENCES KHACHHANG(MAKH) NULL
);
PRINT N'Created: BLOCKED_IPS';
GO

-- SECURITY_LOGS
CREATE TABLE SECURITY_LOGS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ACTION_TYPE VARCHAR(100) NOT NULL,
    MATK INT FOREIGN KEY REFERENCES TAIKHOAN(MATK) NULL,
    IP_ADDRESS VARCHAR(45) NOT NULL,
    DETAILS NVARCHAR(MAX) NULL,
    LOG_TIME DATETIME DEFAULT GETDATE()
);
CREATE INDEX IX_SECURITY_LOGS_TIME ON SECURITY_LOGS(LOG_TIME DESC);
PRINT N'Created: SECURITY_LOGS';
GO

-- AUDIT_LOGS
CREATE TABLE AUDIT_LOGS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TABLE_NAME VARCHAR(100) NOT NULL,
    ACTION VARCHAR(50) NOT NULL,
    OLD_DATA NVARCHAR(MAX) NULL,
    NEW_DATA NVARCHAR(MAX) NULL,
    CHANGED_BY VARCHAR(100) NULL,
    CHANGED_DATE DATETIME DEFAULT GETDATE()
);
PRINT N'Created: AUDIT_LOGS';
GO

-- YCLAMCHUTRO (Landlord Requests)
CREATE TABLE YCLAMCHUTRO (
    MAYC INT IDENTITY(1,1) PRIMARY KEY,
    MAKH INT FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    LYDO NVARCHAR(MAX) NULL,
    TRANGTHAI NVARCHAR(50) DEFAULT N'Chờ duyệt',
    TG_TAO DATETIME DEFAULT GETDATE(),
    TG_DUYET DATETIME NULL,
    NGUOIDUYET INT FOREIGN KEY REFERENCES KHACHHANG(MAKH) NULL
);
PRINT N'Created: YCLAMCHUTRO';
GO

-- ============================================
-- 7. DEFAULT DATA
-- ============================================

-- Insert roles
INSERT INTO VAITRO (TENVT) VALUES
    (N'Admin'),
    (N'Khách hàng'),
    (N'Chủ trọ');

-- Create admin account (password: Admin@123)
-- Salt: fixed for demo, in production use random UUID
DECLARE @ADMIN_SALT VARCHAR(36) = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890';
DECLARE @ADMIN_HASH VARBINARY(32) = HASHBYTES('SHA2_256', 'Admin@123' + @ADMIN_SALT);

INSERT INTO TAIKHOAN (USERNAME, PASSWORD_HASH, PASSWORD_SALT, TG_TAO)
VALUES ('admin@phongtro.vn', @ADMIN_HASH, @ADMIN_SALT, GETDATE());

INSERT INTO KHACHHANG (MATK, MAVT, HOTEN, EMAIL, SDT, TRANGTHAI)
VALUES (1, 1, N'Administrator', 'admin@phongtro.vn', '0900000000', 1);

PRINT N'✅ Created default admin account: admin@phongtro.vn / Admin@123';
GO

-- ============================================
-- 8. STORED PROCEDURES
-- ============================================

-- SP: Secure Login
CREATE OR ALTER PROCEDURE SP_SECURE_LOGIN
    @EMAIL VARCHAR(200),
    @PASSWORD VARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MATK INT, @MAKH INT, @STORED_HASH VARBINARY(32), @SALT VARCHAR(36);
    DECLARE @IS_LOCKED BIT, @LOCK_TIME DATETIME;

    -- Get account info
    SELECT @MATK = TK.MATK, @STORED_HASH = TK.PASSWORD_HASH, @SALT = TK.PASSWORD_SALT,
           @IS_LOCKED = TK.IS_LOCKED, @LOCK_TIME = TK.LOCK_TIME
    FROM TAIKHOAN TK
    INNER JOIN KHACHHANG KH ON TK.MATK = KH.MATK
    WHERE KH.EMAIL = @EMAIL AND KH.TRANGTHAI = 1;

    IF @MATK IS NULL
    BEGIN
        SELECT 0 AS Success, N'Email không tồn tại' AS Message;
        RETURN;
    END

    -- Check if locked
    IF @IS_LOCKED = 1 AND (@LOCK_TIME IS NULL OR @LOCK_TIME > GETDATE())
    BEGIN
        SELECT 0 AS Success, N'Tài khoản đang bị khóa' AS Message;
        RETURN;
    END

    -- Auto-unlock if lock expired
    IF @IS_LOCKED = 1 AND @LOCK_TIME <= GETDATE()
    BEGIN
        UPDATE TAIKHOAN SET IS_LOCKED = 0, LOCK_TIME = NULL, FAILED_LOGIN_COUNT = 0
        WHERE MATK = @MATK;
    END

    -- Verify password
    IF @STORED_HASH = HASHBYTES('SHA2_256', @PASSWORD + @SALT)
    BEGIN
        -- Success: Reset failed count, update last login
        UPDATE TAIKHOAN
        SET FAILED_LOGIN_COUNT = 0, LAST_LOGIN_TIME = GETDATE()
        WHERE MATK = @MATK;

        SELECT KH.MAKH, KH.HOTEN, KH.EMAIL, VT.TENVT AS VAITRO,
               TK.TWO_FACTOR_ENABLED, 1 AS Success, N'OK' AS Message
        FROM KHACHHANG KH
        INNER JOIN TAIKHOAN TK ON KH.MATK = TK.MATK
        INNER JOIN VAITRO VT ON KH.MAVT = VT.MAVT
        WHERE KH.MATK = @MATK;
    END
    ELSE
    BEGIN
        -- Failed: Increment counter
        UPDATE TAIKHOAN
        SET FAILED_LOGIN_COUNT = ISNULL(FAILED_LOGIN_COUNT, 0) + 1
        WHERE MATK = @MATK;

        -- Lock if too many failures (5+)
        IF (SELECT FAILED_LOGIN_COUNT FROM TAIKHOAN WHERE MATK = @MATK) >= 5
        BEGIN
            UPDATE TAIKHOAN
            SET IS_LOCKED = 1, LOCK_TIME = DATEADD(MINUTE, 15, GETDATE())
            WHERE MATK = @MATK;
        END

        SELECT 0 AS Success, N'Mật khẩu không đúng' AS Message;
    END
END;
GO

-- SP: Change Password
CREATE OR ALTER PROCEDURE SP_CHANGE_PASSWORD
    @MAKH INT,
    @OLD_PASSWORD VARCHAR(100),
    @NEW_PASSWORD VARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MATK INT, @STORED_HASH VARBINARY(32), @SALT VARCHAR(36);
    DECLARE @NEW_SALT VARCHAR(36) = NEWID();

    SELECT @MATK = TK.MATK, @STORED_HASH = TK.PASSWORD_HASH, @SALT = TK.PASSWORD_SALT
    FROM TAIKHOAN TK
    INNER JOIN KHACHHANG KH ON TK.MATK = KH.MATK
    WHERE KH.MAKH = @MAKH;

    IF @MATK IS NULL
    BEGIN
        RAISERROR(N'Tài khoản không tồn tại', 16, 1);
        RETURN;
    END

    -- Verify old password
    IF @STORED_HASH != HASHBYTES('SHA2_256', @OLD_PASSWORD + @SALT)
    BEGIN
        RAISERROR(N'Mật khẩu cũ không đúng', 16, 1);
        RETURN;
    END

    -- Update with new password and new salt
    UPDATE TAIKHOAN
    SET PASSWORD_HASH = HASHBYTES('SHA2_256', @NEW_PASSWORD + @NEW_SALT),
        PASSWORD_SALT = @NEW_SALT
    WHERE MATK = @MATK;

    UPDATE KHACHHANG SET LAST_PASSWORD_CHANGE = GETDATE() WHERE MAKH = @MAKH;

    SELECT 1 AS Success, N'Đổi mật khẩu thành công' AS Message;
END;
GO

-- SP: Log Failed Login
CREATE OR ALTER PROCEDURE SP_LOG_FAILED_LOGIN
    @IP_ADDRESS VARCHAR(45),
    @EMAIL VARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO FAILED_LOGIN_ATTEMPTS (IP_ADDRESS, USERNAME_OR_EMAIL, ATTEMPT_TIME)
    VALUES (@IP_ADDRESS, @EMAIL, GETDATE());

    -- Auto-block IP if 10+ failures in 1 hour
    DECLARE @FAIL_COUNT INT;
    SELECT @FAIL_COUNT = COUNT(*) FROM FAILED_LOGIN_ATTEMPTS
    WHERE IP_ADDRESS = @IP_ADDRESS AND ATTEMPT_TIME >= DATEADD(HOUR, -1, GETDATE());

    IF @FAIL_COUNT >= 10
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM BLOCKED_IPS WHERE IP_ADDRESS = @IP_ADDRESS)
        BEGIN
            INSERT INTO BLOCKED_IPS (IP_ADDRESS, REASON, BLOCKED_UNTIL)
            VALUES (@IP_ADDRESS, 'Too many failed logins', DATEADD(MINUTE, 30, GETDATE()));
        END
    END
END;
GO

-- SP: Check IP Blocked
CREATE OR ALTER PROCEDURE SP_CHECK_IP_BLOCKED
    @IP_ADDRESS VARCHAR(45)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1 FROM BLOCKED_IPS
        WHERE IP_ADDRESS = @IP_ADDRESS
        AND (BLOCKED_UNTIL IS NULL OR BLOCKED_UNTIL > GETDATE())
    )
        SELECT 1 AS IsBlocked;
    ELSE
        SELECT 0 AS IsBlocked;
END;
GO

-- SP: Cleanup Old Logs
CREATE OR ALTER PROCEDURE SP_CLEANUP_OLD_LOGS
AS
BEGIN
    SET NOCOUNT ON;

    -- Delete failed attempts older than 7 days
    DELETE FROM FAILED_LOGIN_ATTEMPTS WHERE ATTEMPT_TIME < DATEADD(DAY, -7, GETDATE());

    -- Delete login history older than 90 days
    DELETE FROM LOGIN_HISTORY WHERE TIMESTAMP < DATEADD(DAY, -90, GETDATE());

    -- Delete expired blocked IPs
    DELETE FROM BLOCKED_IPS WHERE BLOCKED_UNTIL < GETDATE();

    -- Delete security logs older than 180 days
    DELETE FROM SECURITY_LOGS WHERE LOG_TIME < DATEADD(DAY, -180, GETDATE());

    PRINT N'Cleanup completed';
END;
GO

PRINT N'✅ Created stored procedures';
GO

-- ============================================
-- 9. TRIGGERS FOR AUDIT
-- ============================================

-- Audit trigger for TAIKHOAN
CREATE OR ALTER TRIGGER TRG_AUDIT_TAIKHOAN
ON TAIKHOAN
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO AUDIT_LOGS (TABLE_NAME, ACTION, OLD_DATA, NEW_DATA, CHANGED_DATE)
    SELECT 'TAIKHOAN', 'UPDATE',
           (SELECT d.MATK, d.USERNAME, d.IS_LOCKED, d.FAILED_LOGIN_COUNT FOR JSON PATH),
           (SELECT i.MATK, i.USERNAME, i.IS_LOCKED, i.FAILED_LOGIN_COUNT FOR JSON PATH),
           GETDATE()
    FROM inserted i
    INNER JOIN deleted d ON i.MATK = d.MATK;
END;
GO

-- Audit trigger for PHONGTRO
CREATE OR ALTER TRIGGER TRG_AUDIT_PHONGTRO
ON PHONGTRO
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @ACTION VARCHAR(50);

    IF EXISTS (SELECT * FROM inserted) AND EXISTS (SELECT * FROM deleted)
        SET @ACTION = 'UPDATE';
    ELSE IF EXISTS (SELECT * FROM inserted)
        SET @ACTION = 'INSERT';
    ELSE
        SET @ACTION = 'DELETE';

    INSERT INTO AUDIT_LOGS (TABLE_NAME, ACTION, OLD_DATA, NEW_DATA, CHANGED_DATE)
    SELECT 'PHONGTRO', @ACTION,
           CASE WHEN @ACTION IN ('UPDATE', 'DELETE')
                THEN (SELECT * FROM deleted FOR JSON PATH) ELSE NULL END,
           CASE WHEN @ACTION IN ('INSERT', 'UPDATE')
                THEN (SELECT * FROM inserted FOR JSON PATH) ELSE NULL END,
           GETDATE();
END;
GO

PRINT N'✅ Created audit triggers';
GO

-- ============================================
-- 10. DATABASE USER & PERMISSIONS (OPTIONAL)
-- ============================================
-- NOTE: Only run this section if you have SA/admin permissions
-- Otherwise, use your existing database user

/*
-- Uncomment and run as SA if you need a new app user:

USE master;
GO

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'phongtro_app')
BEGIN
    CREATE LOGIN phongtro_app WITH PASSWORD = 'PhongTro@SecurePass2024!';
END
GO

USE [QuanLyChoThuePhongTro];
GO

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'phongtro_app')
BEGIN
    CREATE USER phongtro_app FOR LOGIN phongtro_app;
END
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::dbo TO phongtro_app;
GRANT EXECUTE ON SCHEMA::dbo TO phongtro_app;
GO
*/

-- ============================================
-- SUMMARY
-- ============================================

PRINT N'';
PRINT N'============================================';
PRINT N'✅ DATABASE SETUP COMPLETE';
PRINT N'============================================';
PRINT N'';
PRINT N'Admin Account:';
PRINT N'  Email: admin@phongtro.vn';
PRINT N'  Password: Admin@123';
PRINT N'============================================';
GO
