-- ============================================
-- PHONGTRO.VN - UPDATE EXISTING DATABASE
-- Run this to add missing columns to existing tables
-- ============================================

USE [QuanLyChoThuePhongTro];
GO

PRINT N'Starting database update...';
GO

-- ============================================
-- 1. ADD MISSING COLUMNS TO TAIKHOAN
-- ============================================

-- Add PASSWORD_SALT if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TAIKHOAN' AND COLUMN_NAME = 'PASSWORD_SALT')
BEGIN
    ALTER TABLE TAIKHOAN ADD PASSWORD_SALT VARCHAR(36) NULL;
    PRINT N'Added PASSWORD_SALT to TAIKHOAN';
END

-- Add IS_LOCKED if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TAIKHOAN' AND COLUMN_NAME = 'IS_LOCKED')
BEGIN
    ALTER TABLE TAIKHOAN ADD IS_LOCKED BIT DEFAULT 0;
    PRINT N'Added IS_LOCKED to TAIKHOAN';
END

-- Add LOCK_TIME if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TAIKHOAN' AND COLUMN_NAME = 'LOCK_TIME')
BEGIN
    ALTER TABLE TAIKHOAN ADD LOCK_TIME DATETIME NULL;
    PRINT N'Added LOCK_TIME to TAIKHOAN';
END

-- Add FAILED_LOGIN_COUNT if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TAIKHOAN' AND COLUMN_NAME = 'FAILED_LOGIN_COUNT')
BEGIN
    ALTER TABLE TAIKHOAN ADD FAILED_LOGIN_COUNT INT DEFAULT 0;
    PRINT N'Added FAILED_LOGIN_COUNT to TAIKHOAN';
END

-- Add TWO_FACTOR_ENABLED if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TAIKHOAN' AND COLUMN_NAME = 'TWO_FACTOR_ENABLED')
BEGIN
    ALTER TABLE TAIKHOAN ADD TWO_FACTOR_ENABLED BIT DEFAULT 0;
    PRINT N'Added TWO_FACTOR_ENABLED to TAIKHOAN';
END

-- Add TWO_FACTOR_SECRET if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TAIKHOAN' AND COLUMN_NAME = 'TWO_FACTOR_SECRET')
BEGIN
    ALTER TABLE TAIKHOAN ADD TWO_FACTOR_SECRET VARCHAR(100) NULL;
    PRINT N'Added TWO_FACTOR_SECRET to TAIKHOAN';
END

-- Add OAUTH columns if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TAIKHOAN' AND COLUMN_NAME = 'OAUTH_PROVIDER')
BEGIN
    ALTER TABLE TAIKHOAN ADD OAUTH_PROVIDER VARCHAR(50) NULL;
    PRINT N'Added OAUTH_PROVIDER to TAIKHOAN';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TAIKHOAN' AND COLUMN_NAME = 'OAUTH_ID')
BEGIN
    ALTER TABLE TAIKHOAN ADD OAUTH_ID VARCHAR(200) NULL;
    PRINT N'Added OAUTH_ID to TAIKHOAN';
END

-- Add login tracking columns if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TAIKHOAN' AND COLUMN_NAME = 'LAST_LOGIN_IP')
BEGIN
    ALTER TABLE TAIKHOAN ADD LAST_LOGIN_IP VARCHAR(45) NULL;
    PRINT N'Added LAST_LOGIN_IP to TAIKHOAN';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TAIKHOAN' AND COLUMN_NAME = 'LAST_LOGIN_TIME')
BEGIN
    ALTER TABLE TAIKHOAN ADD LAST_LOGIN_TIME DATETIME NULL;
    PRINT N'Added LAST_LOGIN_TIME to TAIKHOAN';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'TAIKHOAN' AND COLUMN_NAME = 'TG_TAO')
BEGIN
    ALTER TABLE TAIKHOAN ADD TG_TAO DATETIME DEFAULT GETDATE();
    PRINT N'Added TG_TAO to TAIKHOAN';
END
GO

-- ============================================
-- 2. ADD MISSING COLUMNS TO KHACHHANG
-- ============================================

-- Add SDT if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'SDT')
BEGIN
    ALTER TABLE KHACHHANG ADD SDT VARCHAR(15) NULL;
    PRINT N'Added SDT to KHACHHANG';
END

-- Add NGAYSINH if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'NGAYSINH')
BEGIN
    ALTER TABLE KHACHHANG ADD NGAYSINH DATE NULL;
    PRINT N'Added NGAYSINH to KHACHHANG';
END

-- Add GIOITINH if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'GIOITINH')
BEGIN
    ALTER TABLE KHACHHANG ADD GIOITINH BIT NULL;
    PRINT N'Added GIOITINH to KHACHHANG';
END

-- Add CCCD if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'CCCD')
BEGIN
    ALTER TABLE KHACHHANG ADD CCCD VARCHAR(20) NULL;
    PRINT N'Added CCCD to KHACHHANG';
END

-- Add TG_TAO if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'KHACHHANG' AND COLUMN_NAME = 'TG_TAO')
BEGIN
    ALTER TABLE KHACHHANG ADD TG_TAO DATETIME DEFAULT GETDATE();
    PRINT N'Added TG_TAO to KHACHHANG';
END

PRINT N'';
PRINT N'✅ Database update complete!';
PRINT N'Now try registering again.';
GO

